Clinical-Genomics/gens

- .github/workflows/stage_docker_push.yml
> Change main to master in docker workflow

- gens/config.py
- gens/db/db.py
> db config tweak: host+port->URI & split gens/scout

- gens/load/annotations.py
> Fixes parse_bed to use csv.DictReader correctly

- gens/db/db.py
> Fixes the list of expected database config vars

- gens/load/annotations.py
> Fixes io operation on closed file error

- gens/commands/load.py
> Replaces deprecated mongodb 'remove' function

- gens/db/annotation.py
- gens/load/annotations.py
> Replaces deprecated/removed mongodb functions

- Dockerfile
> Adds gunicorn default command to dockerfile

- .github/workflows/stage_docker_push.yml
> Adds docker build and push for master branch

- Dockerfile
> Adds --chdir to gunicorn command

- assets/js/gens.js
- assets/js/track/variant.js
- gens/api.py
- gens/blueprints/gens/templates/gens.html
- gens/blueprints/gens/views.py
- gens/commands/load.py
- gens/commands/view.py
- gens/db/annotation.py
- gens/db/models.py
- gens/db/samples.py
- gens/openapi/openapi.yaml
> Adds case name as an additional database field

- gens/commands/load.py
> Replaces the last case name

- gens/db/samples.py
OR
1. Doesn't error out when trying to upload an already existing sample.
**Review:**
> store_sample logs DuplicateKeyError (no crash)

- gens/db/samples.py
OR
1. Upgrade gens in S_gens.
1. Check that cg upload gens works on stage.
**Review:**
> Adds msg to LOG.warning

- gens/blueprints/gens/views.py
> Adds indivudual id parameter handling

- .github/workflows/docker_push.yml
- .github/workflows/keep_a_changelog.yml
- .github/workflows/stage_docker_push.yml
- .github/workflows/tests.yml
- CHANGELOG.md
- gens/blueprints/home/templates/home.html
- gens/blueprints/home/views.py
- jest.config.js
- package-lock.json
- package.json
- setup.py
1. visit a case that loads nicely from scout-stage, go back to home page in gens and note that the link back to the case is broken on `master`
2. on this branch, rinse and repeat and note link working
As for the actions, note deprecation warnings missing from Checks.
**Review:**
> individual_id linking from home sample list

- CHANGELOG.md
- assets/js/track/transcript.js
- gens/api.py
- gens/app.py
- gens/errors.py
- gens/load/annotations.py
Looks like we were lagging a few updates from @mhkc! 😊 
**Review:**
> Cherry synk CG-Lund master

- CHANGELOG.md
- gens/templates/generic_abort_error.html
- gens/templates/generic_exception_error.html
- gens/templates/sample_not_found.html
> Removes leading '/' in a few places

- CHANGELOG.md
- README.md
Add some documentation on track loading, fix #25.
**Review:**
> Add some tracks docs

- CHANGELOG.md
- gens/db/annotation.py
- Fix https://github.com/Clinical-Genomics/gens/issues/47
**Review:**
> use sample_id for variant retrieval

- CHANGELOG.md
- assets/js/track/variant.js
> Clear visual clutter by hiding balanced variants

- CHANGELOG.md
- assets/js/navigation.js
> Fix #58 - dont shrink distance on pan over chr start

- CHANGELOG.md
- gens/__version__.py
- setup.cfg
This PR marks a new Gens release. We apply semantic versioning. This is a minor release since it adds or changes functionality in a backwards compatible manner.
**Review:**
> version 2.2

- CHANGELOG.md
- gens/templates/generic_abort_error.html
- gens/templates/generic_exception_error.html
- gens/templates/sample_not_found.html
> Error SVG static path

- CHANGELOG.md
- assets/js/gens.js
- assets/js/track/annotation.js
- assets/js/track/base.js
- assets/js/track/tooltip.js
- assets/js/track/transcript.js
- assets/js/track/utils.js
- assets/js/track/variant.js
- gens/api.py
- gens/blueprints/gens/templates/gens.html
- gens/blueprints/gens/views.py
- gens/blueprints/home/templates/home.html
- gens/blueprints/home/views.py
- gens/config.py
- package-lock.json
- package.json
- setup.py
> Link out variant

- CHANGELOG.md
- gens/__version__.py
- package-lock.json
- package.json
- setup.py
This PR marks a new Gens release. We apply semantic versioning. This is a minor release since it adds new features in a backwards compatible manner.
**Review:**
> bump version

- .github/workflows/docker_push.yml
- .github/workflows/preproc_docker_push.yml
- CHANGELOG.md
- gens/__version__.py
- package-lock.json
- package.json
- setup.py
> fix docker push

- CHANGELOG.md
- gens/db/samples.py
> Reraises DuplicateKeyError when storing sample, and better error message

- CHANGELOG.md
- gens/commands/load.py
- gens/db/samples.py
OR
1. Run `gens load sample` with and without the `--force` flag.
**Review:**
> 72 add force flag to load sample

- CHANGELOG.md
- gens/db/samples.py
> prints warning to stderr when overwriting old entry

- CHANGELOG.md
- gens/db/samples.py
> Fixes update_one call

- CHANGELOG.md
- gens/db/samples.py
> Fixes delete sample info logging message

- CHANGELOG.md
- gens/blueprints/home/templates/home.html
- gens/blueprints/home/views.py
> Fixes "# samples loaded into gens"

- CHANGELOG.md
- assets/js/track/variant.js
> 52 intratrack stacking not working for variants track

- CHANGELOG.md
- assets/js/track/base.js
- assets/js/track/variant.js
> Center variant description text in view, not only on variant

- CHANGELOG.md
- Dockerfile
> Fix #100 - skip broken extra syslog from docker gunicorn
